### ISSUE TITLE
Attempted connection to http://192.168.0.7:9000/ from the web app fails

### ISSUE THREAD

**Issue by runeksvendsen** [streamium/paystream#39]
When I run Paystream like so:

    sudo docker run -ti --expose=8000 dockerfile/nodejs-bower-gulp /bin/bash -c "git clone https://github.com/streamium/paystream.git; cd paystream/; yes | bower --force --silent --allow-root install; python -m SimpleHTTPServer"

and access the web app from http://$CONTAINER_IP:8000/app/ using Chrome 41.0.2267.0 dev (64-bit) on Ubuntu 14.04, I see the following errors in the Chrome web dev console:

    GET http://172.17.0.11:8000/assets/images/background-images/1.jpg 404 (File not found)          jquery.js:5241
    POST http://192.168.0.7:9000/lwjd5qra8257b9/testnameonetwothreee/kab4iumak1x4unmi/id?i=0 net::ERR_CONNECTION_TIMED_OUT          peer.min.js:1
    we have an error                   provider.js:62
    WebSocket connection to 'ws://192.168.0.7:9000/peerjs?key=lwjd5qra8257b9&id=testnameonetwothreee&token=kab4iumak1x4unmi' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT            peer.min.js:1

After the above messages appear in the console, the web page shows an error message, saying:

    Channel name is taken, please pick a different one

**Comment by esneider** [comment]
The error you are seeing is caused by not having properly setuped the peerjs server. Right now it's pointing to a local server, but you can change it to a non-local one by removing these lines: https://github.com/streamium/paystream/blob/master/app/config.js#L7-L8

Sorry about this, but the project isn't ready yet. It will be soon though!
